require 'set'

require 'savon'
require 'netsuite_new/version'
require 'netsuite_new/errors'
require 'netsuite_new/utilities'
require 'netsuite_new/utilities/data_center'
require 'netsuite_new/utilities/strings'
require 'netsuite_new/rest/utilities/roles'
require 'netsuite_new/rest/utilities/request'

module NetSuiteNew
  autoload :Configuration, 'netsuite_new/configuration'
  autoload :Response,      'netsuite_new/response'

  module Namespaces
    autoload :ActSched,       'netsuite_new/namespaces/act_sched'
    autoload :FileCabinet,    'netsuite_new/namespaces/file_cabinet'
    autoload :ListAcct,       'netsuite_new/namespaces/list_acct'
    autoload :ListRel,        'netsuite_new/namespaces/list_rel'
    autoload :ListSupport,    'netsuite_new/namespaces/list_support'
    autoload :ListWebsite,    'netsuite_new/namespaces/list_website'
    autoload :PlatformCommon, 'netsuite_new/namespaces/platform_common'
    autoload :PlatformCore,   'netsuite_new/namespaces/platform_core'
    autoload :TranBank,       'netsuite_new/namespaces/tran_bank'
    autoload :TranCust,       'netsuite_new/namespaces/tran_cust'
    autoload :TranEmp,        'netsuite_new/namespaces/tran_emp'
    autoload :TranGeneral,    'netsuite_new/namespaces/tran_general'
    autoload :CommGeneral,    'netsuite_new/namespaces/comm_general'
    autoload :TranInvt,       'netsuite_new/namespaces/tran_invt'
    autoload :TranSales,      'netsuite_new/namespaces/tran_sales'
    autoload :TranPurch,      'netsuite_new/namespaces/tran_purch'
    autoload :SetupCustom,    'netsuite_new/namespaces/setup_custom'
    autoload :ListEmp,        'netsuite_new/namespaces/list_emp'
    autoload :ListMkt,        'netsuite_new/namespaces/list_mkt'
  end

  module Support
    autoload :Actions,    'netsuite_new/support/actions'
    autoload :Attributes, 'netsuite_new/support/attributes'
    autoload :Fields,     'netsuite_new/support/fields'
    autoload :Sublist,    'netsuite_new/support/sublist'
    autoload :RecordRefs, 'netsuite_new/support/record_refs'
    autoload :Records,    'netsuite_new/support/records'
    autoload :Requests,   'netsuite_new/support/requests'
    autoload :SearchResult, 'netsuite_new/support/search_result'
    autoload :Country,      'netsuite_new/support/country'
  end

  module Actions
    autoload :AbstractAction,    'netsuite_new/actions/abstract_action'
    autoload :Add,              'netsuite_new/actions/add'
    autoload :AttachFile,       'netsuite_new/actions/attach_file'
    autoload :Delete,           'netsuite_new/actions/delete'
    autoload :DeleteList,       'netsuite_new/actions/delete_list'
    autoload :Get,              'netsuite_new/actions/get'
    autoload :GetDeleted,       'netsuite_new/actions/get_deleted'
    autoload :GetAll,           'netsuite_new/actions/get_all'
    autoload :GetList,          'netsuite_new/actions/get_list'
    autoload :GetSelectValue,   'netsuite_new/actions/get_select_value'
    autoload :Initialize,       'netsuite_new/actions/initialize'
    autoload :Update,           'netsuite_new/actions/update'
    autoload :UpdateList,       'netsuite_new/actions/update_list'
    autoload :Upsert,           'netsuite_new/actions/upsert'
    autoload :UpsertList,       'netsuite_new/actions/upsert_list'
    autoload :Search,           'netsuite_new/actions/search'
    autoload :Login,            'netsuite_new/actions/login'
  end

  module Records
    autoload :AssemblyItem,                     'netsuite_new/records/assembly_item'
    autoload :AssemblyBuild,                    'netsuite_new/records/assembly_build'
    autoload :AssemblyComponent,                'netsuite_new/records/assembly_component'
    autoload :AssemblyComponentList,            'netsuite_new/records/assembly_component_list'
    autoload :AssemblyUnbuild,                  'netsuite_new/records/assembly_unbuild'
    autoload :Account,                          'netsuite_new/records/account'
    autoload :AccountingPeriod,                 'netsuite_new/records/accounting_period'
    autoload :Address,                          'netsuite_new/records/address'
    autoload :BaseRefList,                      'netsuite_new/records/base_ref_list'
    autoload :BillAddress,                      'netsuite_new/records/bill_address'
    autoload :BillingSchedule,                  'netsuite_new/records/billing_schedule'
    autoload :BillingScheduleMilestone,         'netsuite_new/records/billing_schedule_milestone'
    autoload :BillingScheduleMilestoneList,     'netsuite_new/records/billing_schedule_milestone_list'
    autoload :BillingScheduleRecurrence,        'netsuite_new/records/billing_schedule_recurrence'
    autoload :BillingScheduleRecurrenceList,    'netsuite_new/records/billing_schedule_recurrence_list'
    autoload :Bin,                              'netsuite_new/records/bin'
    autoload :BinNumber,                        'netsuite_new/records/bin_number'
    autoload :BinNumberList,                    'netsuite_new/records/bin_number_list'
    autoload :BinTransfer,                      'netsuite_new/records/bin_transfer'
    autoload :BinTransferInventory,             'netsuite_new/records/bin_transfer_inventory'
    autoload :BinTransferInventoryList,         'netsuite_new/records/bin_transfer_inventory_list'
    autoload :CashSale,                         'netsuite_new/records/cash_sale'
    autoload :CashSaleItem,                     'netsuite_new/records/cash_sale_item'
    autoload :CashSaleItemList,                 'netsuite_new/records/cash_sale_item_list'
    autoload :CashRefund,                       'netsuite_new/records/cash_refund'
    autoload :CashRefundItem,                   'netsuite_new/records/cash_refund_item'
    autoload :CashRefundItemList,               'netsuite_new/records/cash_refund_item_list'
    autoload :Campaign,                         'netsuite_new/records/campaign'
    autoload :Classification,                   'netsuite_new/records/classification'
    autoload :CostCategory,                     'netsuite_new/records/cost_category'
    autoload :CreditMemo,                       'netsuite_new/records/credit_memo'
    autoload :CreditMemoApply,                  'netsuite_new/records/credit_memo_apply'
    autoload :CreditMemoApplyList,              'netsuite_new/records/credit_memo_apply_list'
    autoload :CreditMemoItem,                   'netsuite_new/records/credit_memo_item'
    autoload :CreditMemoItemList,               'netsuite_new/records/credit_memo_item_list'
    autoload :CustomField,                      'netsuite_new/records/custom_field'
    autoload :CustomFieldList,                  'netsuite_new/records/custom_field_list'
    autoload :CustomList,                       'netsuite_new/records/custom_list'
    autoload :CustomRecord,                     'netsuite_new/records/custom_record'
    autoload :CustomRecordRef,                  'netsuite_new/records/custom_record_ref'
    autoload :CustomRecordType,                 'netsuite_new/records/custom_record_type'
    autoload :CustomListCustomValue,            'netsuite_new/records/custom_list_custom_value'
    autoload :CustomListCustomValueList,        'netsuite_new/records/custom_list_custom_value_list'
    autoload :Customer,                         'netsuite_new/records/customer'
    autoload :CustomerAddressbook,              'netsuite_new/records/customer_addressbook'
    autoload :CustomerAddressbookList,          'netsuite_new/records/customer_addressbook_list'
    autoload :CustomerCategory,                 'netsuite_new/records/customer_category'
    autoload :CustomerCreditCards,              'netsuite_new/records/customer_credit_cards'
    autoload :CustomerCreditCardsList,          'netsuite_new/records/customer_credit_cards_list'
    autoload :CustomerCurrency,                 'netsuite_new/records/customer_currency'
    autoload :CustomerCurrencyList,             'netsuite_new/records/customer_currency_list'
    autoload :CustomerDeposit,                  'netsuite_new/records/customer_deposit'
    autoload :CustomerDepositApplyList,         'netsuite_new/records/customer_deposit_apply_list'
    autoload :CustomerDepositApply,             'netsuite_new/records/customer_deposit_apply'
    autoload :CustomerPartnersList,             'netsuite_new/records/customer_partners_list'
    autoload :CustomerPayment,                  'netsuite_new/records/customer_payment'
    autoload :CustomerPaymentApply,             'netsuite_new/records/customer_payment_apply'
    autoload :CustomerPaymentApplyList,         'netsuite_new/records/customer_payment_apply_list'
    autoload :CustomerPaymentCredit,            'netsuite_new/records/customer_payment_credit'
    autoload :CustomerPaymentCreditList,        'netsuite_new/records/customer_payment_credit_list'
    autoload :CustomerPartner,                  'netsuite_new/records/customer_partner'
    autoload :CustomerRefund,                   'netsuite_new/records/customer_refund'
    autoload :CustomerRefundApply,              'netsuite_new/records/customer_refund_apply'
    autoload :CustomerRefundApplyList,          'netsuite_new/records/customer_refund_apply_list'
    autoload :CustomerRefundDeposit,            'netsuite_new/records/customer_refund_deposit'
    autoload :CustomerRefundDepositList,        'netsuite_new/records/customer_refund_deposit_list'
    autoload :CustomerStatus,                   'netsuite_new/records/customer_status'
    autoload :CustomerPartner,                  'netsuite_new/records/customer_partner'
    autoload :CustomerSalesTeam,                'netsuite_new/records/customer_sales_team'
    autoload :CustomerSalesTeamList,            'netsuite_new/records/customer_sales_team_list'
    autoload :ContactList,                      'netsuite_new/records/contact_list'
    autoload :Contact,                          'netsuite_new/records/contact'
    autoload :ContactAddressbook,               'netsuite_new/records/contact_addressbook'
    autoload :ContactAddressbookList,           'netsuite_new/records/contact_addressbook_list'
    autoload :ContactRole,                      'netsuite_new/records/contact_role'
    autoload :ContactAccessRoles,               'netsuite_new/records/contact_access_roles'
    autoload :ContactAccessRolesList,           'netsuite_new/records/contact_access_roles_list'
    autoload :Currency,                         'netsuite_new/records/currency'
    autoload :CurrencyRate,                     'netsuite_new/records/currency_rate'
    # ... continuing with all other records
  end

  module Passports
    autoload :User,  'netsuite_new/passports/user'
    autoload :Token, 'netsuite_new/passports/token'
  end

  def self.configure(&block)
    Configuration.instance.reset!
    yield(Configuration.instance) if block_given?
  end
end
